# -*- coding: utf-8 -*-
"""Logic2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xixbCelly0xCRG5VxjXYE8tIo0MRjtE
"""

# Costom Function

def crange(a,b):
    return range(a,b+1)

def printnln(a):
    print(a, end="")

# Soal 1

# angka ganjil n * 2 + 1 / n * 2 - 1
#for n in crange(1,9):
 # j = n * 2 - 1
  # print(j)

for y in crange(1,9):
  for x in crange(1,9):
    if x == y:
        j = x * 2 -1
        printnln(j)
    else:
        printnln("_")
  print()

# soal 2

for y in crange(1,9):
  for x in crange(1,9):
    if x == 9 - (y - 1):
      n = x * 2 - 2
      printnln(n)
    else:
      printnln("_")
  print()

# soal 3

for y in crange(1,9):
  for x in crange(1,9):
    if x == y:
      j = x * 2 - 1
      printnln(j)
    elif x == 9 - (y - 1):
      n = x * 2 - 2
      printnln(n)
    else:
      printnln ("_")
  print()

# soal 4

for y in crange(1,9):
  for x in crange(1,9):
    if x == y or x == 5:
      j = y * 2 - 1
      printnln(j)
    elif x == 9 - (y - 1) or y == 5:
      n = x * 2 - 2
      printnln(n)
    else:
      printnln ("__")
  print()

# Soal 5

for y in crange(1,9):
  for x in crange(1,9):
    if x <= y:
        j = x * 2 - 1
        printnln(j)
    else:
        printnln("__")
  print()

# SOAL 6

for y in crange(1,9):
  for x in crange(1,9):
    if x >= 9 - (y - 1):
      v = 9 - (y - 1)
      n = v * 2 - 2
      printnln(n)
    else:
      printnln("_")
  print()

# Soal 7

for y in crange(1,9):
  for x in crange(1,9):
    if x == y:
      j = y * 2 - 1
      printnln(j)
    elif x == 9 - (y - 1):
      n = x * 2 - 2
      printnln(n)
    elif x > y and x <  9 - (y - 1):
      printnln("A")
    elif x < y and x >  9 - (y - 1):
      printnln("B")
    else:
      printnln("_")
  print()

# Soal 8

for y in crange(1,9):
  for x in crange(1,9):
    if x == y:
      j = y * 2 - 1
      printnln(j)
    elif x == 9 - (y - 1):
      n = x * 2 - 2
      printnln(n)
    elif x < y and x <  9 - (y - 1):
      printnln("A")
    elif x > y and x >  9 - (y - 1):
      printnln("B")
    else:
      printnln("_")
  print()