# -*- coding: utf-8 -*-
"""Logic1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnyR_ttNa26Oxe8Z4oZChv_lTurAw49T
"""

# soal 1

for y in range(1,10):
  for x in range(1,10):
    if x == y:
      print("*", end="")
    else:
      print("_", end="")

  print()

# soal 2

for y in range(1,10):
  for x in range(1,10):
    if x == 9 - (y - 1):
      print("*", end="")
    else:
      print("_", end="")

  print()

def crange(a,b):
    return range(a,b + 1)

def printnln(a):
    print(a, end="")

# soal 2

for y in crange(1,9):
  for x in crange(1,9):
    if x == 9 - (y - 1):
      printnln("*")
    else:
      printnln("_")
  print()

for y in crange(1,9):
  for x in crange(1,9):
    if x == 9 - (y - 1):
      printnln("*")
    else:
      printnln("_")
  print()

# soal 3 (or)

for y in crange(1,9):
  for x in crange(1,9):
    if x == y or x == 9 - (y - 1):
        printnln("*")
    else:
        printnln("_")
  print()

# (and)

for y in crange(1,9):
  for x in crange(1,9):
    if x == y and x == 9 - (y - 1):
        printnln("*")
    else:
        printnln("_")
  print()

# (elif)

for y in crange(1,9):
  for x in crange(1,9):
    if x == y:
        printnln("*")
    elif x == 9 - (y - 1):
        printnln("*")
    else:
        printnln("_")
  print()

# soal 4

for y in crange(1,9):
  for x in crange(1,9):
    if x == y:
        printnln("*")
    elif x == 9 - (y - 1):
        printnln("*")
    elif x == 5:
        printnln("*")
    elif y == 5:
        printnln("*")
    else:
        printnln("_")
  print()

# soal 5

for y in crange(1,9):
  for x in crange(1,9):
    if x <= y:
      printnln("*")
    else:
      printnln("_")
  print()

# soal 6

for y in crange(1,9):
  for x in crange(1,9):
    if x >= 9 - (y - 1):
      printnln("*")
    else:
      printnln("_")

  print()

# soal 7

for y in crange(1,9):
  for x in crange(1,9):
    if x >= y and x <= 9 - (y - 1):
      printnln("*")
    elif x <= y and x >=  9 - (y - 1):
      printnln("*")
    else:
      printnln("_")
  print()

def crange(a,b):
    return range(a,b + 1)

def printnln(a):
    print(a, end="")

# soal 8

for y in crange(1,9):
  for x in crange(1,9):
    if x <= y and x <= 9 - (y - 1):
      printnln("*")
    elif x >= y and x >= 9 - (y - 1):
      printnln("*")
    else:
      printnln("_")
  print()